---
title: "Hyphae Labs Automated Report Generator"
author: "IMB"
date: "2022-11-08"
output: html_document
---

```{r setup, include=FALSE}
################################################################################
# Load Necessary Libraries
################################################################################
library(reticulate)
library(plotly)
library(dplyr)
library(googlesheets4)
library(stringr)
library(filesstrings)
use_python('C:/Users/theda/AppData/Local/Programs/Python/Python310/python.exe')
################################################################################

################################################################################
# Function to Load the Google Sheets Database
################################################################################
load_google_database = function() {
  # Load in the Processing Data Batch Google Sheet 
  preProcDF = googledrive::drive_get('Hyphae Labs Merge CURRENT') %>% 
  read_sheet()
  procDF = preProcDF
  return(procDF)}
################################################################################

################################################################################
# Function to generate a Working Dataframe from Sample ID List
################################################################################
stats_df_generator = function(sample_id_range,procDF) {
  replicate_df = procDF[0,]
  working_stats_df = data.frame('Sample_ID' = c(''), 'Sample_Name' = c(''),
                                'Cultivar' = c(''), 'Client_Name' = c(''),
                                'Species' = c(''), 'Generation_Date' = c(''),
                                'Client_Notes' = c(''), 'Lab_Description' = c(''),
                                'Homogenized_Description' = c(''),
                                'Norbaeocystin_mg_g' = c(''), 'Norbaeocystin_SD' = c(''),
                                'Baeocystin_mg_g' = c(''), 'Baeocystin_SD' = c(''),
                                'Psilocybin_mg_g' = c(''), 'Psilocybin_SD' = c(''),
                                'Aeruginascin_mg_g' = c(''), 'Aeruginascin_SD' = c(''),
                                'Adenosine_mg_g' = c(''), 'Adenosine_SD' = c(''),
                                'Five_Methoxy_DMT_mg_g' = c(''), 'Five_Methoxy_DMT_SD' = c(''),
                                'Cordycepin_mg_g' = c(''), 'Cordycepin_SD' = c(''),
                                'Psilocin_mg_g' = c(''), 'Psilocin_SD' = c(''),
                                'Norpsilocin_mg_g' = c(''), 'Norpsilocin_SD' = c(''),
                                'Four_HTMT_mg_g' = c(''), 'Four_HTMT_SD' = c(''),
                                'Tryptamine_mg_g' = c(''), 'Tryptamine_SD' = c(''),
                                'Bufotenin_mg_g' = c(''), 'Bufotenin_SD' = c(''),
                                'NN_DMT_mg_g' = c(''), 'NN_DMT_SD' = c(''))
  working_stats_df = working_stats_df[-1,]
  for (sample_id in sample_id_range){
    sample_working_stats_df = working_stats_df[1,]
    sample_working_stats_df$'Sample_ID' = sample_id
    # Only Target A, B, and C Replicates (others are different experiments)
    replicate_list = c('A', 'B', 'C')
    replicate_name = '{DEFAULT NAME}'
    replicate_cultivar = '{DEFAULT CULTIVAR}'
    replicate_client = '{DEFAULT CLIENT}'
    replicate_species = '{DEFAULT SPECIES}'
    replicate_gen_date = '{DEFAULT GENERATION DATE}'
    replicate_client_notes = '{DEFAULT CLIENT NOTES}'
    replicate_lab_desc = '{DEFAULT LAB DESC}'
    replicate_homog_desc = '{DEFAULT HOMOG DESC}'
    replicate_report_type = '{DEFAULT REPORT}'
    for (replicate in replicate_list) {
      replicate_id = paste(sample_id, replicate, sep = '')
      replicate_name = procDF[which(procDF$Sample_ID == replicate_id), ]$Sample_Name
      replicate_cultivar = procDF[which(procDF$Sample_ID == replicate_id), ]$Cultivar
      replicate_client = procDF[which(procDF$Sample_ID == replicate_id), ]$Client_Name
      replicate_species = procDF[which(procDF$Sample_ID == replicate_id), ]$Species_of_Origin
      replicate_gen_date = procDF[which(procDF$Sample_ID == replicate_id), ]$Generation_Date
      replicate_client_notes = procDF[which(procDF$Sample_ID == replicate_id), ]$Client_Notes
      replicate_lab_desc = procDF[which(procDF$Sample_ID == replicate_id), ]$Lab_Description
      replicate_homog_desc = procDF[which(procDF$Sample_ID == replicate_id), ]$Homogenized_Description
      replicate_report_type = procDF[which(procDF$Sample_ID == replicate_id), ]$Report_Type
      replicate_df = rbind(replicate_df, procDF[which(procDF$Sample_ID == replicate_id), ])}
    if (nrow(replicate_df) > 1){
      # Generate Mean Data for the Sample
      sample_working_stats_df$'Norbaeocystin_mg_g' = mean(replicate_df$'Norbaeocystin_mg_g')
      sample_working_stats_df$'Baeocystin_mg_g' = mean(replicate_df$'Baeocystin_mg_g')
      sample_working_stats_df$'Psilocybin_mg_g' = mean(replicate_df$'Psilocybin_mg_g')
      sample_working_stats_df$'Aeruginascin_mg_g' = mean(replicate_df$'Aeruginascin_mg_g')
      sample_working_stats_df$'Adenosine_mg_g' = mean(replicate_df$'Adenosine_mg_g')
      sample_working_stats_df$'Five_Methoxy_DMT_mg_g' = mean(replicate_df$'Five_Methoxy_DMT_mg_g')
      sample_working_stats_df$'Cordycepin_mg_g' = mean(replicate_df$'Cordycepin_mg_g')
      sample_working_stats_df$'Psilocin_mg_g' = mean(replicate_df$'Psilocin_mg_g')
      sample_working_stats_df$'Norpsilocin_mg_g' = mean(replicate_df$'Norpsilocin_mg_g')
      sample_working_stats_df$'Four_HTMT_mg_g' = mean(replicate_df$'Four_Hydroxy_TMT_mg_g')
      sample_working_stats_df$'Tryptamine_mg_g' = mean(replicate_df$'Tryptamine_mg_g')
      sample_working_stats_df$'Bufotenin_mg_g' = mean(replicate_df$'Bufotenin_mg_g')
      sample_working_stats_df$'NN_DMT_mg_g' = mean(replicate_df$'NN_DMT_mg_g')
      # Generate Standard Deviation Data for the Sample
      sample_working_stats_df$'Norbaeocystin_SD' = sd(replicate_df$'Norbaeocystin_mg_g')
      sample_working_stats_df$'Baeocystin_SD' = sd(replicate_df$'Baeocystin_mg_g')
      sample_working_stats_df$'Psilocybin_SD' = sd(replicate_df$'Psilocybin_mg_g')
      sample_working_stats_df$'Aeruginascin_SD' = sd(replicate_df$'Aeruginascin_mg_g')
      sample_working_stats_df$'Adenosine_SD' = sd(replicate_df$'Adenosine_mg_g')
      sample_working_stats_df$'Five_Methoxy_DMT_SD' = sd(replicate_df$'Five_Methoxy_DMT_mg_g')
      sample_working_stats_df$'Cordycepin_SD' = sd(replicate_df$'Cordycepin_mg_g')
      sample_working_stats_df$'Psilocin_SD' = sd(replicate_df$'Psilocin_mg_g')
      sample_working_stats_df$'Norpsilocin_SD' = sd(replicate_df$'Norpsilocin_mg_g')
      sample_working_stats_df$'Four_HTMT_SD' = sd(replicate_df$'Four_Hydroxy_TMT_mg_g')
      sample_working_stats_df$'Tryptamine_SD' = sd(replicate_df$'Tryptamine_mg_g')
      sample_working_stats_df$'Bufotenin_SD' = sd(replicate_df$'Bufotenin_mg_g')
      sample_working_stats_df$'NN_DMT_SD' = sd(replicate_df$'NN_DMT_mg_g')
    } else {
      # Generate Mean Data for the Sample
      sample_working_stats_df$'Norbaeocystin_mg_g' = replicate_df$'Norbaeocystin_mg_g'
      sample_working_stats_df$'Baeocystin_mg_g' = replicate_df$'Baeocystin_mg_g'
      sample_working_stats_df$'Psilocybin_mg_g' = replicate_df$'Psilocybin_mg_g'
      sample_working_stats_df$'Aeruginascin_mg_g' = replicate_df$'Aeruginascin_mg_g'
      sample_working_stats_df$'Adenosine_mg_g' = replicate_df$'Adenosine_mg_g'
      sample_working_stats_df$'Five_Methoxy_DMT_mg_g' = replicate_df$'Five_Methoxy_DMT_mg_g'
      sample_working_stats_df$'Cordycepin_mg_g' = replicate_df$'Cordycepin_mg_g'
      sample_working_stats_df$'Psilocin_mg_g' = replicate_df$'Psilocin_mg_g'
      sample_working_stats_df$'Norpsilocin_mg_g' = replicate_df$'Norpsilocin_mg_g'
      sample_working_stats_df$'Four_HTMT_mg_g' = replicate_df$'Four_Hydroxy_TMT_mg_g'
      sample_working_stats_df$'Tryptamine_mg_g' =replicate_df$'Tryptamine_mg_g'
      sample_working_stats_df$'Bufotenin_mg_g' = replicate_df$'Bufotenin_mg_g'
      sample_working_stats_df$'NN_DMT_mg_g' = replicate_df$'NN_DMT_mg_g'
      # Generate Standard Deviation Data for the Sample
      sample_working_stats_df$'Norbaeocystin_SD' = NA
      sample_working_stats_df$'Baeocystin_SD' = NA
      sample_working_stats_df$'Psilocybin_SD' = NA
      sample_working_stats_df$'Aeruginascin_SD' = NA
      sample_working_stats_df$'Adenosine_SD' = NA
      sample_working_stats_df$'Five_Methoxy_DMT_SD' = NA
      sample_working_stats_df$'Cordycepin_SD' = NA
      sample_working_stats_df$'Psilocin_SD' = NA
      sample_working_stats_df$'Norpsilocin_SD' = NA
      sample_working_stats_df$'Four_HTMT_SD' = NA
      sample_working_stats_df$'Tryptamine_SD' = NA
      sample_working_stats_df$'Bufotenin_SD' = NA
      sample_working_stats_df$'NN_DMT_SD' = NA}
    # Append the Working Stats Dataframe with the Sample's Mean and SD Data 
    sample_working_stats_df$'Sample_Name' = replicate_name
    sample_working_stats_df$'Cultivar' = replicate_cultivar
    sample_working_stats_df$'Client_Name' = replicate_client
    sample_working_stats_df$'Species' = replicate_species
    sample_working_stats_df$'Generation_Date' = replicate_gen_date
    sample_working_stats_df$'Client_Notes' = replicate_client_notes
    sample_working_stats_df$'Lab_Description' = replicate_lab_desc
    sample_working_stats_df$'Homogenized_Description' = replicate_homog_desc
    sample_working_stats_df$'Report_Type' = replicate_report_type
    working_stats_df = rbind(working_stats_df, sample_working_stats_df)}
  return(working_stats_df)}
################################################################################

################################################################################
# Function to save SVG of Ploty Graphic using JavaScript & Firefox
################################################################################
save_plotly_svg <- function(plot, file_name) {
  gc()
  export(p = plot, file = file_name,
         selenium = RSelenium::rsDriver(browser = "firefox"))
  gc()}
################################################################################

################################################################################
# Function to Generate All Graphics from Dataframe Row
################################################################################
gen_graphics_from_row <- function(row) {
    report_type = row$Report_Type
  sample_name = row$Sample_Name
  sample_id = row$Sample_ID
  sample_client = row$Client_Name 
  sample_species = row$Species
  sample_cultivar = row$Cultivar 
  sample_gen_date = row$Generation_Date 
  sample_cult_desc = row$Client_Notes 
  sample_lab_desc = row$Lab_Description
  sample_homog_desc = row$Homogenized_Description
  # ORDER: N,N-DMT, Psilocybin, Psilocin, Bufotenin, 5-MEO-DMT
  known_mg_g_values= c(row$NN_DMT_mg_g, row$Psilocybin_mg_g, row$Psilocin_mg_g, row$Bufotenin_mg_g, row$Five_Methoxy_DMT_mg_g)
  known_SD_values= c(row$NN_DMT_SD, row$Psilocybin_SD, row$Psilocin_SD, row$Bufotenin_SD, row$Five_Methoxy_DMT_SD)
  # ORDER: Adenosine, Cordycepin, Tryptamine, Baocystin, Norpsilocin, Norbaeocystin, 4-HT (Pending Validation '#6495ED'), Aeruginascin, 4-HTMT
  other_mg_g_values= c(row$Adenosine_mg_g, row$Cordycepin_mg_g, row$Tryptamine_mg_g, row$Baeocystin_mg_g, row$Norpsilocin_mg_g, row$Norbaeocystin_mg_g, row$Aeruginascin_mg_g, row$Four_HTMT_mg_g)
  other_SD_values= c(row$Adenosine_SD, row$Cordycepin_SD, row$Tryptamine_SD, row$Baeocystin_SD, row$Norpsilocin_SD, row$Norbaeocystin_SD, row$Aeruginascin_SD, row$Four_HTMT_SD)
  
  # Generate Immutable Properties 
  files_to_copy = c()
  known_names = c('N,N-DMT', 'Psilocybin', 'Psilocin', 'Bufotenin', '5-MEO-DMT')
  known_colors = c('#BA55D3', '#6A5ACD', '#9370DB', '#9932CC', '#8B008B')
  known_font = c('white','white','white','white','white')
  known_mg_g_sum = round(sum(known_mg_g_values),1)
  known_SD_sum = round(sum(known_SD_values),1)
  other_names = c('Adenosine', 'Cordycepin', 'Tryptamine', 'Baeocystin', 'Norpsilocin', 'Norbaeocystin', 'Aeruginascin', '4-HTMT')
  other_colors = c('#FF8C00', '#FFD700', '#D2B48C', '#2F4F4F', '#008080', '#4682B4', '#0000FF', '#00008B')
  other_font = c('black','black','black','white','white','white', 'white','white')
  other_mg_g_sum = round(sum(other_mg_g_values),1)
  other_SD_sum = round(sum(other_SD_values),1)
  
  # Create Sample Data Frames
  known_data <- data.frame(Compound_Name = known_names,
                           mg_g_value = known_mg_g_values,
                           SD_value = known_SD_values,
                           Legend_Color = known_colors,
                           Legend_Font_Color = known_font)
  known_data = known_data %>% mutate_if(is.numeric, round, digits = 1)
  other_data <- data.frame(Compound_Name = other_names,
                           mg_g_value = other_mg_g_values,
                           SD_value = other_SD_values,
                           Legend_Color = other_colors,
                           Legend_Font_Color = other_font)
  
  other_data = other_data %>% mutate(across(where(is.numeric), ~ round(., 1)))
  final_data <- rbind(known_data,other_data)
  
  # Generate Donut Chart
  donut_plot = plot_ly(height = 565, width = 500) %>%
    add_pie(labels = known_data$Compound_Name, values = known_data$mg_g_value,
            textinfo = 'label+value',
            text = '',
            insidetextfont = list(color = '#FFFFFF'),
            type = 'pie', hole = 0.65, sort = F,
            marker = list(colors = known_data$Legend_Color,
                          line = list(width = 0.25,
                                      text = known_data$mg_g_value)),
            textfont = list(size = 18),
            textposition ='inside',
            domain = list(x = c(0.15, 0.85),
                          y = c(0.15, 0.85))) %>%
    add_pie(labels = other_data$Compound_Name, values = other_data$mg_g_value,
            textinfo = 'label+value',
            text = '',
            type = 'pie', hole = 0.725, sort = F,
            marker = list(colors = other_data$Legend_Color,
                          line = list(width = 0.25,
                                      text=other_data$mg_g_value)),
            textfont = list(size = 18),
            textposition ='inside')
  donut_plot <- layout(donut_plot, title=paste(sample_id, sample_name,'\n CHEMICAL PROFILE', sep = ' '), font=list(size=18))
  donut_plot<- layout(donut_plot, annotations=list(x = 0.5, y = 0.49, text = 'Known Entheogenic Alakaloids TOTAL',
                                                   "showarrow" = F, font = list(size = 11)))
  donut_plot<- layout(donut_plot, annotations=list(x = 0.5, y = 0.56, text = paste(known_mg_g_sum,'±',known_SD_sum,'mg/g',sep=''),
                                                   "showarrow" = F, font = list(size = 28.5)))
  donut_plot<- layout(donut_plot, annotations=list(x = 0.5, y = 0.37, text = 'Other Serotonergic Activity TOTAL',
                                                   "showarrow" = F, font = list(size = 10)))
  donut_plot<- layout(donut_plot, annotations=list(x = 0.5, y = 0.42, text = paste(other_mg_g_sum,'±',other_SD_sum,'mg/g',sep=''),
                                                   "showarrow" = F, font = list(size = 25, color='darkgrey')))
  donut_plot<- layout(donut_plot,shapes = list(
    list(type = 'line',
         line = list(color='black'), 
         x0=0.3, y0=0.46,
         x1=0.7, y1=0.46)))
  donut_plot<- layout(donut_plot,
                      autosize = F,
                      margin = list(l = 0, r = 5, b = 0, t = 75, pad = 4),showlegend = FALSE)
  donut_plot
  donut_plot_name = paste(sample_id, 'donut_plot.svg', sep = '-')
  save_plotly_svg(donut_plot, donut_plot_name)
  files_to_copy = append(files_to_copy, donut_plot_name)
  
  # Generate Legend Table
  legend_df <- final_data[final_data$mg_g_value !=0,]
  legend_df <- legend_df[order(legend_df$mg_g_value, decreasing=TRUE),]
  legend_df$mg_g_SD_value = paste(legend_df$mg_g_value, '±', legend_df$SD_value, 'mg/g', sep='')
  legend_table <- plot_ly(
    height = 565,
    width = 493,
    type = 'table',
    columnwidth = c(3,2),
    header = list(
      values = c('<b>Compound Name<b>','<b>mg/g Value<b>'),
      align = 'center',
      fill = list(color = 'black'),
      font = list(family = "Arial", size = 20, color = "white")),
    cells = list(
      values = rbind(legend_df$Compound_Name,legend_df$mg_g_SD_value),
      align = c('center', rep('center', ncol(legend_df))),
      line = list(color = "black", width = 1),
      fill = list(color = list(legend_df$Legend_Color,'white')),
      font = list(family = "Arial", size = 24, color = list(legend_df$Legend_Font_Color,'black')),
      height = 50))
  legend_table<- layout(legend_table,
                        autosize = F,
                        margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                        showlegend = FALSE)
  legend_table
  legend_table_name = paste(sample_id, 'legend_table.svg', sep = '-')
  save_plotly_svg(legend_table, legend_table_name)
  files_to_copy = append(files_to_copy, legend_table_name)
  
  # Generate Dose Table
  dose_fruit_g = c(0.1,0.2,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,5.0)
  dose_active_mg = c()
  dose_category = c()
  dose_color = c()
  dose_font_color = c()
  dose_column = c()
  for (fruit_g in dose_fruit_g) {
    dose_mg = known_mg_g_sum*fruit_g
    dose_active_mg = append(dose_active_mg, dose_mg)
    if (dose_mg <= 1.5){
      use_category = '<b>Explore<b>'
      use_color = '#ADFF2F'
      font_color = 'black'
      column_width = 75}
    else if (dose_mg <= 6.0){
      use_category = '<b>Micro<b>'
      use_color = '#00FF00'
      font_color = 'black'
      column_width = 75}
    else if (dose_mg <= 25.0){
      use_category = '<b>Rec/Ou<b>t'
      use_color = '#00ffff'
      font_color = 'black'
      column_width = 75}
    else if (dose_mg <= 40.0){
      use_category = '<b>Therapy<b>'
      use_color = '#0000ff'
      font_color = 'white'
      column_width = 75}
    else if (dose_mg <= 50.0){
      use_category = '<b>Spirit<b>'
      use_color = '#9932CC'
      font_color = 'white'
      column_width = 75}
    else {
      use_category = '<b>Deep<b>'
      use_color = '#ff00ff'
      font_color = 'white'
      column_width = 75}
    dose_category = append(dose_category, use_category)
    dose_color = append(dose_color,use_color)
    dose_font_color = append(dose_font_color,font_color)
    dose_column = append(dose_column,column_width)}
  dose_fruit_g = round(dose_fruit_g,1)
  dose_active_mg = round(dose_active_mg,1)
  dose_fruit_g = c('Fruit g Dose',dose_fruit_g)
  dose_active_mg = c('<b>Expected Psychoactive Tryptamines mg<b>',dose_active_mg)
  dose_category = c('<b>Recommended Use<b>',dose_category)
  dose_color = c('black',dose_color)
  dose_font_color = c('white',dose_font_color)
  dose_column = c(150,dose_column)
  dose_table <- plot_ly(
    height = 210,
    width = 1325,
    type = 'table',
    columnwidth = dose_column,
    header = list(
      values = dose_fruit_g,
      align = c('right','center'),
      fill = list(color = c('black','white')),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = 30, color = c('white','black')),
      height = 40),
    cells = list(
      values = cbind(dose_active_mg,dose_category),
      align = c('right','center'),
      line = list(width = 0, color = 'black'),
      fill = list(color = dose_color),
      font = list(family = "Arial", size = c(15,25), color = dose_font_color, type='bold'),
      height = 50))
  dose_table <- layout(dose_table,
                       title=paste(sample_id, sample_name,'\nRECOMMENDED DOSAGE CHART',sep = ' '),
                       font=list(size=18))
  dose_table <- layout(dose_table,
                       autosize = F,
                       margin = list(l = 0, r = 0, b = 0, t = 75, pad = 4),
                       showlegend = FALSE)
  dose_table
  dose_table_name = paste(sample_id, 'dose_table.svg', sep = '-')
  save_plotly_svg(dose_table, dose_table_name)
  files_to_copy = append(files_to_copy, dose_table_name)
  
  # Generate Sample Name & ID Table
  sample_table_name_id_path = paste(sample_id, 'sample_table_name_id.svg', sep = '-')
  sample_table_name_id <- plot_ly(
    height = 75,
    width = 1325,
    type = 'table',
    columnwidth = c(451,1000),
    header = list(
      values = c('ITEM ID & NAME:', paste(sample_id,sample_name,sep=' - ')),
      align = c('right','left'),
      fill = list(color = 'black'),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = c(35,45), color = 'white'),
      height = 75))
  sample_table_name_id <- layout(sample_table_name_id,
                         autosize = F,
                         margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                         showlegend = FALSE)
  sample_table_name_id
  save_plotly_svg(sample_table_name_id, sample_table_name_id_path)
  files_to_copy = append(files_to_copy, sample_table_name_id_path)

  # Generate Sample Client Table
  sample_table_client_path = paste(sample_id, 'sample_table_client.svg', sep = '-')
  sample_table_client <- plot_ly(
    height = 70,
    width = 1325,
    type = 'table',
    columnwidth = c(451,1000),
    header = list(
      values = c('CULTIVATOR/PRODUCER:',sample_client),
      align = c('right','left'),
      fill = list(color = c('lightgrey', 'white')),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = c(30,45), color = 'black', type = 'bold'),
      height = 70))
  sample_table_client <- layout(sample_table_client,
                         autosize = F,
                         margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                         showlegend = FALSE)
  sample_table_client 
  save_plotly_svg(sample_table_client, sample_table_client_path)
  files_to_copy = append(files_to_copy, sample_table_client_path)
  
  # Generate Sample Species Table
  sample_table_species_path = paste(sample_id, 'sample_table_species.svg', sep = '-')
  sample_table_species <- plot_ly(
    height = 70,
    width = 1325,
    type = 'table',
    columnwidth = c(451,1000),
    header = list(
      values = c('SPECIES:',sample_species),
      align = c('right','left'),
      fill = list(color = c('lightgrey', 'white')),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = c(30,45), color = 'black', type = 'bold'),
      height = 70))
  sample_table_species <- layout(sample_table_species,
                         autosize = F,
                         margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                         showlegend = FALSE)
  sample_table_species 
  save_plotly_svg(sample_table_species, sample_table_species_path)
  files_to_copy = append(files_to_copy, sample_table_species_path)

  # Generate Sample Cultivar Table
  sample_table_cultivar_path = paste(sample_id, 'sample_table_cultivar.svg', sep = '-')
  sample_table_cultivar <- plot_ly(
    height = 70,
    width = 1325,
    type = 'table',
    columnwidth = c(451,1000),
    header = list(
      values = c('CULTIVAR:',sample_cultivar),
      align = c('right','left'),
      fill = list(color = c('lightgrey', 'white')),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = c(30,45), color = 'black', type = 'bold'),
      height = 70))
  sample_table_cultivar <- layout(sample_table_cultivar,
                         autosize = F,
                         margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                         showlegend = FALSE)
  sample_table_cultivar 
  save_plotly_svg(sample_table_cultivar, sample_table_cultivar_path)
  files_to_copy = append(files_to_copy, sample_table_cultivar_path)
  
  # Generate Sample Generation Date Path
  sample_table_gen_date_path = paste(sample_id, 'sample_table_gen_date.svg', sep = '-')
  sample_table_gen_date <- plot_ly(
    height = 70,
    width = 1325,
    type = 'table',
    columnwidth = c(451,1000),
    header = list(
      values = c('GENERATION DATE:',sample_gen_date),
      align = c('right','left'),
      fill = list(color = c('lightgrey', 'white')),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = c(30,45), color = 'black', type = 'bold'),
      height = 70))
  sample_table_gen_date <- layout(sample_table_gen_date,
                         autosize = F,
                         margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                         showlegend = FALSE)
  sample_table_gen_date 
  save_plotly_svg(sample_table_gen_date, sample_table_gen_date_path)
  files_to_copy = append(files_to_copy, sample_table_gen_date_path)
  
  # Generate Top Half of Description Table
  description_table_top_name = paste(sample_id, 'description_table_top.svg', sep = '-')
  description_table_top <- plot_ly(
    height = 80,
    width = 1325,
    type = 'table',
    columnwidth = c(451,1000),
    header = list(
      values = c('DESCRIPTION:', sample_cult_desc),
      align = c('right','left'),
      fill = list(color = c('lightgrey','white')),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = c(30,25), color = 'black'),
      height = 75))
  description_table_top <- layout(description_table_top,
                                  autosize = F,
                                  margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                                  showlegend = FALSE)
  description_table_top
  save_plotly_svg(description_table_top, description_table_top_name)
  files_to_copy = append(files_to_copy, description_table_top_name)
  
  # Generate Bottom Half of Description Table
  description_table_bot_name = paste(sample_id, 'description_table_bot.svg', sep = '-')
  description_table_bot <- plot_ly(
    height = 425,
    width = 1325,
    type = 'table',
    columnwidth = c(451,273,451,273),
    header = list(
      values = c('', sample_lab_desc,'',sample_homog_desc),
      align = 'left',
      fill = list(color = 'white'),
      line = list(width = 1, color = 'black'),
      font = list(family = "Arial", size = 25, color = 'black'),
      height = 405))
  description_table_bot <- layout(description_table_bot,
                                  autosize = F,
                                  margin = list(l = 0, r = 0, b = 0, t = 0, pad = 4),
                                  showlegend = FALSE)
  description_table_bot
  save_plotly_svg(description_table_bot, description_table_bot_name)
  files_to_copy = append(files_to_copy, description_table_bot_name)
  
  # Move Generated Images to their appropriate Google Drive folder
  origin_dir <- c("C:/Users/theda/Downloads")
  workspace_dir = "H:/My Drive/HL Data Files/AUTOMATION WORKSPACE/"
  sample_dir <- c(paste(workspace_dir,report_type,' - ',sample_id,' - ',sample_name,sep=''))
  
  if (file.exists(sample_dir)){
    # specifying the working directory
    print(paste(sample_dir,'FOLDER EXISTS!',sep=' '))
  } else {
    
    # create a new sub directory inside
    # the main path
    dir.create(file.path(sample_dir))
    print(paste(sample_dir,'FOLDER EXISTS!',sep=' '))
  }
  
  for (i in 1:length(files_to_copy)) {
    files_to_copy[i] = paste(origin_dir,files_to_copy[i], sep='/')
  }
  
  file.copy(from=files_to_copy, to=sample_dir, 
            overwrite = TRUE, recursive = FALSE, 
            copy.mode = TRUE)
  
  for (i in 1:length(files_to_copy)) {
    file.remove(files_to_copy[i])}
}
```

```{r setup, include=FALSE}
################################################################################
#
# RUN MAIN LOADER AND REPLICATE PARSER FOR SAMPLE LIST
#
################################################################################

if (exists('procDF') && is.data.frame(get('procDF'))){
  print('DATABASE ALREADY LOADED')
} else {
  procDF=load_google_database()}

sample_id_range = c('CUP161','CUP162','CUP163')

working_stats_df = stats_df_generator(sample_id_range,procDF)

################################################################################

################################################################################
#
# RUN MAIN GRAPHICS GENERATOR FOR WORKING STATS DATAFRAME
#
################################################################################
for (i in 1:nrow(working_stats_df)) {
  row = working_stats_df[i,]
  row[is.na(row)] <- 0
  #gen_graphics_from_row(row)
}
```
